### ISSUE TITLE
Client crashes when websocket fails to connect

### ISSUE THREAD

**Issue by paulbarclay** [loomnetwork/loom-js#68]
When the client fails to connect on a websocket, I'd expect some retry behaviour on the websocket connection, rather than a hard crash with an unhandled error.

Here's the error:
`error:{"kind":"error","url":"ws://127.0.0.1:46657/websocket","error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":46657}}`

Here's the call stack:

```
server_1  | [web   ] events.js:188
server_1  | [web   ]       throw err;
server_1  | [web   ]       ^
server_1  | [web   ] 
server_1  | [web   ] Error: Unhandled "error" event. ([object Object])
server_1  | [web   ]     at Client.emit (events.js:186:19)
server_1  | [web   ]     at Client._emitNetEvent (/srv/server/node_modules/loom-js/dist/client.js:725:18)
server_1  | [web   ]     at WSRPCClient.<anonymous> (/srv/server/node_modules/loom-js/dist/client.js:125:26)
server_1  | [web   ]     at emitTwo (events.js:126:13)
server_1  | [web   ]     at WSRPCClient.emit (events.js:214:7)
server_1  | [web   ]     at Client.<anonymous> (/srv/server/node_modules/loom-js/dist/internal/ws-rpc-client.js:151:65)
server_1  | [web   ]     at Client.emit (/srv/server/node_modules/rpc-websockets/node_modules/eventemitter3/index.js:181:35)
server_1  | [web   ]     at WebSocket.<anonymous> (/srv/server/node_modules/rpc-websockets/dist/lib/client.js:430:35)
server_1  | [web   ]     at emitOne (events.js:116:13)
server_1  | [web   ]     at WebSocket.emit (events.js:211:7)
server_1  | [web   ]     at ClientRequest.req.on (/srv/server/node_modules/rpc-websockets/node_modules/ws/lib/websocket.js:535:10)
server_1  | [web   ]     at emitOne (events.js:116:13)
server_1  | [web   ]     at ClientRequest.emit (events.js:211:7)
server_1  | [web   ]     at Socket.socketErrorListener (_http_client.js:387:9)
server_1  | [web   ]     at emitOne (events.js:116:13)
server_1  | [web   ]     at Socket.emit (events.js:211:7)
server_1  | [web   ]     at emitErrorNT (internal/streams/destroy.js:64:8)
server_1  | [web   ]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
server_1  | [web   ]     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by eduardonunesp** [comment]
We're going to check that retry, for now you can prevent that behavior by adding a listener to the error event:
```js
this.client = new Client(
  'default',
  'ws://127.0.0.1:46657/websocket',
  'ws://127.0.0.1:9999/queryws',
)

this.client.on('error', msg => {
  console.error('Error on connect to client', msg)
  console.warn('Please verify if loom command is running')
})
```

**Comment by eduardonunesp** [comment]
Right now we recommend using the `client.on('error', ...)` to always handle cases like connections issues, maybe in the future this can be changed, also you'll be able to tweak socket connections params if necessary, i.e. 

```js
const writer = createJSONRPCClient({ 
  protocols: [{ url: 'http://extdev-plasma-us1.dappchains.com:80/rpc' }], 
  autoConnect: true, 
  requestTimeout: 1000
})

const reader = createJSONRPCClient({ 
  protocols: [{ url: 'http://extdev-plasma-us1.dappchains.com:80/query' }], 
  autoConnect: true, 
  requestTimeout: 1000 
})

const client = new Client(
  'default',
  writer,
  reader
)

client.on('error', e => console.log(e))
```
